# Generated by Django 4.1 on 2023-12-09 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_booking_bookingdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Inventory',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='BookingDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 9, 16, 5, 35, 363236, tzinfo=datetime.timezone.utc)),
        ),
    ]
